
drop  TABLE tmp_fraud_weekly_recommendation;

CREATE TABLE tmp_fraud_weekly_recommendation
(
  advertiser_name         VARCHAR(500),
  advertiser_id INT,
  site_name               VARCHAR(500),
  site_id INT,
  publisher_name          VARCHAR(500),
  publisher_id INT,
  traffic_week            DATE,
  Adv_Site_Pub_Wk_Qty     BIGINT,
  publisher_sub_campaign  VARCHAR(500),
  publisher_sub_publisher VARCHAR(500),
  country_name            VARCHAR(100),
  country_sub_publisher   VARCHAR(600),
  Subset_Qty              BIGINT,
  pct_of_traffic          NUMERIC(22, 2),
  q1_time                 INT,
  q2_time                 INT,
  q3_time                 INT,
  q4_time                 INT,
  ratio_q2_over_q3        NUMERIC(14, 3),
  linear_exception        VARCHAR(20),
  hijack_exception        VARCHAR(41),
  Qty_per_20_second       VARCHAR(600),
  Qty_per_5_minute        VARCHAR(600),
  Qty_per_houR            VARCHAR(600),
      pct_aphone NUMERIC(21, 2),
      pct_iphone NUMERIC(21, 2),
      pct_atab NUMERIC(21, 2),
      pct_itab NUMERIC(21, 2),
    pct_fingerprint NUMERIC(21, 2),
    pct_deviceid NUMERIC(21, 2),
    pct_referrer NUMERIC(21, 2),
    pct_inline NUMERIC(21, 2),
    pct_preload NUMERIC(21, 2),
    pct_other NUMERIC(21, 2),
       pct_approved NUMERIC(21, 2),
       pct_app_30_day NUMERIC(21, 2),
       pct_app_reinstall NUMERIC(21, 2),
       pct_rej_jailbroke NUMERIC(21, 2),
       pct_rej_invalid NUMERIC(21, 2),
       pct_rej_unattr NUMERIC(21, 2),
       pct_rej_already NUMERIC(21, 2)
);
